changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Discovery and evaluation improvements
      labels:
        - discovery
        - evaluation
    - title: Fixes
      labels:
        - bug
    - title: Documentation and community
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
